### ISSUE TITLE
preload alert - corrupted area color

### ISSUE THREAD

**Issue by ghost** [smad2005/PoeHud#15]
It doesn't change on the fly, only after reopening the hud.

ty,

**Comment by smad2005** [comment]
I did on area changing. A little bit later i will make "on the fly" (but it will be a little less efficient).
linked to  #9

**Comment by ghost** [comment]
Great job, tested all and it's working like a charm, :)

ps: why do you say it's less efficient to change colors in real time straight from menu ? is there anything better ?

Thank you,

**Comment by smad2005** [comment]
Originally, I didn't want to do so, just because there will be an additional function call, and this will be used only for corrupted area.
