### ISSUE TITLE
Antlr4 updating

### ISSUE THREAD

**Issue by H4vC** [smad2005/PoeHud#29]
Yo I haven't been around for a long time and I haven't a clue how to deal with antlr but poe filter parsing is broken and I was wondering if you'd have time explaining really quick how to do antlr4

**Comment by smad2005** [comment]
Yo
You can look:
- https://programming-pages.com/2013/12/14/antlr-4-with-c-and-visual-studio-2012/
- https://github.com/sharwell/antlr4cs/wiki/Installation

I'm not sure, but maybe cs generation from antlr still not working in VS2015 ( http://stackoverflow.com/questions/35973460/visual-studio-2015-c-sharp-antlr ) and only work on VS2013 with .net4.5

For testing [grammar](https://github.com/smad2005/PoeFilterParser/blob/master/PoeFilter.g4) there some tools http://www.antlr.org/tools.html i used `ANTLRWorks 2`.

**Comment by H4vC** [comment]
Thanks a bunch mate.

Cheers.

**Comment by H4vC** [comment]
Yeah I can't seem to get it to work with neither VS2015 nor 2013 having followed the instructions on antler4's github.
Would you mind taking a jab at it at some point ?
Thanks a bunch we're over at https://github.com/TehCheat/PoEHUD/ .

**Comment by smad2005** [comment]
I think @i2um1 will fix it

**Comment by i2um1** [comment]
Let's see what can I do.

**Comment by smad2005** [comment]
>poe filter parsing is broken

@H4vC can you attach a file that doesn't work?

**Comment by i2um1** [comment]
Show
	Corrupted True

**Comment by H4vC** [comment]
Corrupted and Identified are the two new keywords that the antlr grammar file doesn't handle.
They are both either true or false.

**Comment by smad2005** [comment]
@H4vC fixed, https://github.com/smad2005/PoeFilterParser/commits/master
Even added small tests for these files https://github.com/smad2005/PoeFilterParser/tree/master/Tests/PoeFilterParser.NUnit.IntegrationTests/Filters

**Comment by H4vC** [comment]
thanks a bunch mate, I'll go try it out.
