### ISSUE TITLE
прелоад

### ISSUE THREAD

**Issue by WowicX** [smad2005/PoeHud#4]
не отображаются на гангрене прелоад и иконки на карте

**Comment by smad2005** [comment]
Покаместь не планирую обновлять гарену снг, так как программой пользуются всего 7 человек. Может будет под steam, а сейчас это не рентабельно.

**Comment by WowicX** [comment]
зачем тогда копируеш оригинал?  и да пользуетсо больше просто мало о ней знают  там вроде баг в том что клиент отображаетсо поверх иконок и исправить ето ето пара строчек кода ( я не прогер   я етих строчек не знаю )

**Comment by smad2005** [comment]
> зачем тогда копируеш оригинал? 

https://github.com/H4vC/PoeHud/graphs/contributors 

> там вроде баг в том что клиент отображаетсо поверх иконок и исправить ето ето пара строчек кода

Ничего не понял

**Comment by i2um1** [comment]
> ето ето пара строчек кода

Откуда такая уверенность? Предлагаю тебе самостоятельно исправить эти строчки.
