### ISSUE TITLE
Qol

### ISSUE THREAD

**Issue by smad2005** [smad2005/PoeHud#8]
> how about adding the visual colors and new positions...like this : 
> ![344f3964-3cf7-11e5-9c6e-f48c9d5ecaca](https://cloud.githubusercontent.com/assets/1619549/9181749/5ddbe2fe-3faf-11e5-859b-1fa3bea5368c.png)
> ![30023776-3cf7-11e5-98a1-6fe5ae30a802](https://cloud.githubusercontent.com/assets/1619549/9181750/5ddd404a-3faf-11e5-993d-32e2b17e998d.png)
> ![2950762584-example](https://cloud.githubusercontent.com/assets/1619549/9181902/2b733398-3fb0-11e5-8831-74e6582b7ba7.png)
> 
> Most of the changes are for design purpose, but some of them are useful, like adding colors for drops to match the itemfilter, or colors for preloads when farming a specific mod.

What's new:
- "#" in currency.txt
- Hudskin hardcoded, but added

```
  public static readonly Color MapsColor = new ColorBGRA(222, 184, 135, 0xFF);

        public static readonly Color RGBColor = new ColorBGRA(220, 20, 60, 0xFF);

        public static readonly Color LinkedColor = new ColorBGRA(30, 144, 255, 0xFF);

        public static readonly Color SocketsColor = new ColorBGRA(74, 230, 58, 0xFF);

        public static readonly Color CraftingColor = new ColorBGRA(0, 255, 255, 0xFF);
```

I think need to move those values to config.json and edit  them via menu. (Ps: for now i'm not planning/willing to write itemfilter parser)
- changes in itemAlert plugin ,itemalertSetting
- changes ItemUsefulProperties

**colors for curencies** :  (border color, font color, border width)

```
if (_name.Contains("Chaos Orb") ||
                    _name.Contains("Blessed Orb") ||
                    _name.Contains("Regal Orb") ||
                    _name.Contains("Vaal Orb") ||
                    _name.Contains("Gemcutter's Prism") ||
                    _name.Contains("Orb of Regret") ||
                    _name.Contains("Orb of Alchemy") ||
```

**Jewels rarity**

```
                switch (rarity)
                {
                    case ItemRarity.Rare:
                        frameWidth = 1;
                        frameColor = settings.FrameJewelsColor;
                        fontColor = HudSkin.RareColor;
                        return true;
                    case ItemRarity.Unique:
                        frameWidth = 1;
                        frameColor = HudSkin.UniqueColor;
                        fontColor = HudSkin.UniqueColor;
                        return true;
```
- Changes in colorbotton (need to look)
-  Changes in MenuItem.cs (need to look)
-  Changes in MenuPlugin.cs (need to look)
-  Changes in ToggleButton.cs (need to look)

```
 Color color = node.Value ? settings.EnabledBoxColor : settings.DisabledBoxColor;
```
-  Changes in PreloadAlert,cs (need to look)

```
Settings.corruptedFontColor

corrupted.Add("Corrupted Area                 .");
```

| # | Task Url | Planned |
| --- | --- | --- |
| 1 | Preload alerts with diff colours  #9 | yes |
| 2 | Monster alerts (by mode, by name) with diff colours #11 | yes |
| 3 | Shift the xpBar/clock  left/below of meters #10 | yes |
| 4 | Allow commenting ("#") in currency.txt #13 | yes |
| 5 | Setting for menu (font size, button size, etc) | no |
| 6 | Colours for itemAlert from itemfilter | yes |

**Comment by smad2005** [comment]
```
   public int ReadInt(int addr, params int[] _offsets)
        {
            int num = ReadInt(addr);
            return _offsets.Aggregate(num, (current, num2) => ReadInt(current + num2));
        }

 private bool CompareData(Pattern pattern, byte[] data, int offset)
        {
            return !pattern.Bytes.Where((t, i) => pattern.Mask[i] == 'x' && t != data[offset + i]).Any();
        }


 private static bool HasDebuff(IReadOnlyDictionary
...
 if (!settings.ShowHealthText || life.MaxES == 0) // need go deeper in HealthbarPlugin

```

**Comment by smad2005** [comment]
XpRatePlugin ->  TimeNowPlugin

**Comment by ghost** [comment]
What about this, hard coded masters/strongboxes color, instead of people having to work with hex values :)... what do you think ?
![masters_cr](https://cloud.githubusercontent.com/assets/1595758/9429653/5095f40a-49e0-11e5-8766-edc16a7b9689.jpg)

**Comment by smad2005** [comment]
For now i'm fighting with ~~droplevel, width, height, class~~, without these offsets i can't finish №6.

**Comment by ghost** [comment]
Well, i'm bored...:). I am trying to use textures and colors from the game to make a new look for the hud :)

![newmenu](https://cloud.githubusercontent.com/assets/1595758/9448573/0450ef84-4aa6-11e5-9d9b-2f4507250412.jpg)

Still work in progress ....

**Comment by smad2005** [comment]
wow

**Comment by ghost** [comment]
New look almost done, try this if you have time...: https://github.com/vmv/iHUD
I have few problems anyway, and i don't know how to fix/arrange them.

Thank you,
